global using Nautilus.Assets.PrefabTemplates;
global using UnityEngine.AddressableAssets;
global using System.Collections.Generic;
global using Nautilus.Assets.Gadgets;
global using Sprite = Atlas.Sprite;
global using Nautilus.Extensions;
global using System.Collections;
global using Nautilus.Handlers;
global using Nautilus.Crafting;
global using Nautilus.Utility;
global using static CraftData;
global using BepInEx.Logging;
global using Nautilus.Assets;
global using UnityEngine;
global using System.Linq;
global using HarmonyLib;
global using RamuneLib;
global using BepInEx;
global using System;
//